export interface DocChaseConfig {
  cloneId: string;
  castId: string;
}

export interface DocWorkItem {
  target_clone_id: string;
  cast_id: string;
  prompt: string;
  priority: 'normal' | 'high';
}

export class DocChaseDispatcher {
  constructor(private readonly config: DocChaseConfig) {}

  static parseTaskIntoItems(
    task: string,
    cloneId: string,
    castId: string,
  ): DocWorkItem[] {
    const pathRegex = /(?:packages\/[^\s,]+|src\/[^\s,]+)/g;
    const paths = task.match(pathRegex) ?? [];

    if (paths.length === 0) {
      return [{
        target_clone_id: cloneId,
        cast_id: castId,
        prompt: buildDocPrompt(task),
        priority: 'normal',
      }];
    }

    return paths.map((p) => ({
      target_clone_id: cloneId,
      cast_id: castId,
      prompt: buildDocPrompt(p),
      priority: 'normal' as const,
    }));
  }

  get isDone(): boolean {
    return false;
  }
}

function buildDocPrompt(target: string): string {
  return [
    `Document the public API of \`${target}\`.`,
    '',
    'Include: module purpose, class/function signatures, parameters, return types,',
    'error conditions, state machine transitions (if any), usage examples from tests.',
    '',
    'Output: write to docs/api/ or docs/arch/ as a markdown file.',
    'Start with: "> Auto-generated by documentation-chase clone."',
    'After completing, broadcast docs_ready with the file list.',
  ].join('\n');
}
